site_name: Ryft Roleplay Informatie
site_url: https://regels.ryftroleplay.nl
site_description: 'Ryft Roleplay Regels'
site_author: 'Ryft Roleplay'

copyright: 'Copyright &copy; 2025 Ryft Roleplay | Alle rechten voorbehouden'

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      toggle:
        icon: material/brightness-7
        name: Verwissel naar donkere modus

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      toggle:
        icon: material/brightness-4
        name: Verwissel naar lichte modus
  language: nl
  logo: assets/logo.png
  favicon: assets/logo.png

  features:
    - toc.follow

  icon:
    annotation: material/arrow-right-circle

nav:
  - Server Regels: index.md
  - Tebex terms: tebex.md
  - Categorieën: categorieen.md

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: ""
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
